<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>OkulApplication</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OkulApplication.Domain\OkulApplication.Domain.csproj" />
    <ProjectReference Include="..\OkulApplication.TestBase\OkulApplication.TestBase.csproj" />
  </ItemGroup>

</Project>
